title: "Philippe Béliveau"
baseurl: "/"
theme: "raditian-free-hugo-theme-data-science"
languageCode: "en-us"

params:
  logo:
    text1: "Philippe"
    text2: "Béliveau"
    image: "img/moi.png"
  description: "AI Researcher | Time Series Modeling | Generative Data"
  author: "Philippe Béliveau"
  email: "philbeliv@gmail.com"
  location: "Montreal, Canada"
  linkedin: "https://www.linkedin.com/in/philippe-beliveau/"

  # 🔧 Add this to activate sections
  sections:
    - showcase
    - about
    - experience
    - education
    - testimonial
    - contact

  # 🔧 Optional: enable plugins if available in your theme
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js

menu:
  header:
    - URL: '#about'
      name: About
      weight: 1
    - URL: '#portfolio'
      name: Projects
      weight: 2
    - URL: '#resume'
      name: Resume
      weight: 3
    - URL: '#contact'
      name: Contact
      weight: 4
