title: "Philippe Béliveau"
baseurl: "/"
theme: "raditian-free-hugo-theme"
languageCode: "en-us"

params:
  logo: "img/moi.png"
  description: "AI Researcher | Time Series Modeling | Generative Data"
  author: "Philippe Béliveau"
  email: "philbeliv@gmail.com"
  location: "Montreal, Canada"
  linkedin: "https://www.linkedin.com/in/philippe-beliveau/"

menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 1
    - name: "Projects"
      url: "/project/"
      weight: 2
    - name: "Resume"
      url: "/resume/"
      weight: 3
